### ISSUE TITLE
Garbage input sent to nano as EDITOR on mouse click

### ISSUE THREAD

**Issue by falkTX** [OpenMusicKontrollers/notes.lv2#5]
Using nano as EDITOR and carla v2.3 as plugin host. notes.lv2 is up-to-date to latest git.
Every time I mouse click on the console/bottom-panel, nano adds what appears to be garbage input.

Screenshot follows.

![Screenshot_20210409_155819](https://user-images.githubusercontent.com/1334853/114199664-679f7600-994c-11eb-95b9-7948973bc892.png)

**Comment by ventosus** [comment]
thanks for reporting.

well, those are console mouse events alright, nano just does not seem to support them.

something wrong in console mouse support discovery, I guess

**Comment by ventosus** [comment]
how have you installed that plugin?

you seem to be missing all tool button icons and the correct font...

**Comment by ventosus** [comment]
fixed in d2tk 5a3295fa5b2e0fe4724125e5c8473f1d13d04caa

**Comment by falkTX** [comment]
> how have you installed that plugin?

I just built from latest git.
Using the debian scripts to build as I want to generate a package, the setup step goes with these flags by default:
```
cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu
```

the UI resource files are installed correctly:
```
dh_auto_install -O-Smeson
        cd obj-x86_64-linux-gnu && DESTDIR=/Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2 LC_ALL=C.UTF-8 ninja install
[0/1] Installing files.
Installing notes.so to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing notes_ui.so to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/manifest.ttl to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/notes.ttl to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/notes_ui.ttl to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/clipboard.png to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/copy.png to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/delete.png to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/eye-off.png to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/eye.png to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
Installing /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/obj-x86_64-linux-gnu/save.png to /Shared/Personal/FOSS/Repo/Debian-Plugins/notes.lv2/debian/notes.lv2/usr/lib/lv2/notes.lv2
```

but it seems this build cant load images at all.
what can I investigate regarding this?

**Comment by ventosus** [comment]
> what can I investigate regarding this?

1. exclude that it is a bug in your host (e.g. test with multiple hosts)
2. add a printf("[%s] %s\n", __func__, img_path) at [1] to check whether the file exists at the desired location

[1] https://github.com/OpenMusicKontrollers/notes.lv2/blob/master/subprojects/d2tk/src/backend_nanovg.c#L781

P.s. the README states that the UI needs firasans and firacode TTF fonts. You need to either embed them in the package or when building with font-config support make the package depend on the fonts.

**Comment by falkTX** [comment]
I can test in multiple hosts, but that still doesnt tell me why something would be happening.
I know for sure the image exists, because the option to open it externally works fine.

also, from what I can see I do have firacode fonts installed.
```
$ dpkg -L fonts-firacode
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/fonts-firacode
/usr/share/doc/fonts-firacode/README.md.gz
/usr/share/doc/fonts-firacode/changelog.Debian.gz
/usr/share/doc/fonts-firacode/copyright
/usr/share/doc/fonts-firacode/examples
/usr/share/doc/fonts-firacode/examples/fira_code.css
/usr/share/fonts
/usr/share/fonts/opentype
/usr/share/fonts/opentype/firacode
/usr/share/fonts/opentype/firacode/FiraCode-Bold.otf
/usr/share/fonts/opentype/firacode/FiraCode-Light.otf
/usr/share/fonts/opentype/firacode/FiraCode-Medium.otf
/usr/share/fonts/opentype/firacode/FiraCode-Regular.otf
/usr/share/fonts/opentype/firacode/FiraCode-Retina.otf
/usr/share/fonts-firacode
/usr/share/fonts-firacode/woff
/usr/share/fonts-firacode/woff/FiraCode-Bold.woff
/usr/share/fonts-firacode/woff/FiraCode-Light.woff
/usr/share/fonts-firacode/woff/FiraCode-Medium.woff
/usr/share/fonts-firacode/woff/FiraCode-Regular.woff
/usr/share/fonts-firacode/woff/FiraCode-Retina.woff
/usr/share/fonts-firacode/woff2
/usr/share/fonts-firacode/woff2/FiraCode-Bold.woff2
/usr/share/fonts-firacode/woff2/FiraCode-Light.woff2
/usr/share/fonts-firacode/woff2/FiraCode-Medium.woff2
/usr/share/fonts-firacode/woff2/FiraCode-Regular.woff2
/usr/share/fonts-firacode/woff2/FiraCode-Retina.woff2
```

and font-config is for sure installed:
```
$ dpkg -l | grep fontconfig | awk '{printf $2 "\n"}'
fontconfig
fontconfig-config
libfontconfig1:amd64
libfontconfig1:i386
libfontconfig1-dev:amd64
```

I would rather build without fontconfig though, so I will see about putting the font files inside the lv2 bundle.

**Comment by falkTX** [comment]
FYI jalv.gtk also does not show images.
But I will open a new ticket for this shortly. 

PS: can you update the github remote?

**Comment by ventosus** [comment]
nanovg only supports TrueTypeFonts.

> I would rather build without fontconfig though, so I will see about putting the font files inside the lv2 bundle.

Just disable font config support at build time, and fonts will be put in plugin bundle automagically.

> PS: can you update the github remote?

This is up-to-date, fix for this issue here is in a subproject which will be pulled in
